using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DotWeb.Models
{
    public partial class VehicleOrderDetails
    {
        public int Id { get; set; }
        public int VehicleOrderId { get; set; }
        public string Plan { get; set; }
        public string ProdNumber { get; set; }
        public string OrderNumber { get; set; }
        public string VehicleNumber { get; set; }
        public string DeliveryNumber { get; set; }
        public string VehicleType { get; set; }
        public string EngineType { get; set; }
        public string PlantDispathDate { get; set; }
        public string Interior { get; set; }
        public string Paint { get; set; }
        public string Model { get; set; }
        public string CountryName { get; set; }
        public string EngineNumber { get; set; }
        public string SampleDigit { get; set; }
        public string NumberOfCode { get; set; }
        public string Codes { get; set; }
        public string Codes1 { get; set; }
        public string Codes2 { get; set; }
        public string Codes3 { get; set; }
        public string Codes4 { get; set; }
        public string Codes5 { get; set; }
        public string Codes6 { get; set; }
        public string Codes7 { get; set; }
        public string Codes8 { get; set; }
        public string Codes9 { get; set; }
        public string Codes10 { get; set; }
        public string Codes11 { get; set; }
        public string Codes12 { get; set; }
        public string Codes13 { get; set; }
        public string Codes14 { get; set; }
        public string Codes15 { get; set; }
        public string Codes16 { get; set; }
        public string Codes17 { get; set; }
        public string Codes18 { get; set; }
        public string Codes19 { get; set; }
        public string Codes20 { get; set; }
        public string Codes21 { get; set; }
        public string Codes22 { get; set; }
        public string Codes23 { get; set; }
        public string Codes24 { get; set; }
        public string Codes25 { get; set; }
        public string Codes26 { get; set; }
        public string Codes27 { get; set; }
        public string Codes28 { get; set; }
        public string Codes29 { get; set; }
        public string Codes30 { get; set; }
        public string Codes31 { get; set; }
        public string Codes32 { get; set; }
        public string Codes33 { get; set; }
        public string Codes34 { get; set; }
        public string Codes35 { get; set; }
        public string Codes36 { get; set; }
        public string Codes37 { get; set; }
        public string Codes38 { get; set; }
        public string Codes39 { get; set; }
        public string Codes40 { get; set; }
        public string Codes41 { get; set; }
        public string Codes42 { get; set; }
        public string Codes43 { get; set; }
        public string Codes44 { get; set; }
        public string Codes45 { get; set; }
        public string Codes46 { get; set; }
        public string Codes47 { get; set; }
        public string Codes48 { get; set; }
        public string Codes49 { get; set; }
        public string Codes50 { get; set; }
        public string Codes51 { get; set; }
        public string Codes52 { get; set; }
        public string Codes53 { get; set; }
        public string Codes54 { get; set; }
        public string Codes55 { get; set; }
        public string Codes56 { get; set; }
        public string Codes57 { get; set; }
        public string Codes58 { get; set; }
        public string Codes59 { get; set; }
        public string Codes60 { get; set; }
        public string Codes61 { get; set; }
        public string Codes62 { get; set; }
        public string Codes63 { get; set; }
        public string Codes64 { get; set; }
        public string Codes65 { get; set; }
        public string Codes66 { get; set; }
        public string Codes67 { get; set; }
        public string Codes68 { get; set; }
        public string Codes69 { get; set; }
        public string Codes70 { get; set; }
        public string Codes71 { get; set; }
        public string Codes72 { get; set; }
        public string Codes73 { get; set; }
        public string Codes74 { get; set; }
        public string Codes75 { get; set; }
        public string Codes76 { get; set; }
        public string Codes77 { get; set; }
        public string Codes78 { get; set; }
        public string Codes79 { get; set; }
        public string Codes80 { get; set; }
        public string Codes81 { get; set; }
        public string Codes82 { get; set; }
        public string Codes83 { get; set; }
        public string Codes84 { get; set; }
        public string Codes85 { get; set; }
        public string Codes86 { get; set; }
        public string Codes87 { get; set; }
        public string Codes88 { get; set; }
        public string Codes89 { get; set; }
        public string Codes90 { get; set; }
        public string Codes91 { get; set; }
        public string Codes92 { get; set; }
        public string Codes93 { get; set; }
        public string Codes94 { get; set; }
        public string Codes95 { get; set; }
        public string Codes96 { get; set; }
        public string Codes97 { get; set; }
        public string Codes98 { get; set; }
        public string Codes99 { get; set; }
        public string Codes100 { get; set; }
        public string Codes101 { get; set; }
        public string Codes102 { get; set; }
        public string Codes103 { get; set; }
        public string Codes104 { get; set; }
        public string Codes105 { get; set; }
        public string Codes106 { get; set; }
        public string Codes107 { get; set; }
        public string Codes108 { get; set; }
        public string Codes109 { get; set; }
        public string Codes110 { get; set; }
        public string Codes111 { get; set; }
        public string Codes112 { get; set; }
        public string Codes113 { get; set; }
        public string Codes114 { get; set; }
        public string Codes115 { get; set; }
        public string Codes116 { get; set; }
        public string Codes117 { get; set; }
        public string Codes118 { get; set; }
        public string Codes119 { get; set; }
        public string Codes120 { get; set; }
        public string Codes121 { get; set; }
        public string Codes122 { get; set; }
        public string Codes123 { get; set; }
        public string Codes124 { get; set; }
        public string Codes125 { get; set; }
        public string Codes126 { get; set; }
        public string Codes127 { get; set; }
        public string Codes128 { get; set; }
        public string Codes129 { get; set; }
        public string Codes130 { get; set; }
        public string Codes131 { get; set; }
        public string Codes132 { get; set; }
        public string Codes133 { get; set; }
        public string Codes134 { get; set; }
        public string Codes135 { get; set; }
        public string Codes136 { get; set; }
        public string Codes137 { get; set; }
        public string Codes138 { get; set; }
        public string Codes139 { get; set; }
        public string Codes140 { get; set; }
        public string Codes141 { get; set; }
        public string Codes142 { get; set; }
        public string Codes143 { get; set; }
        public string Codes144 { get; set; }
        public string Codes145 { get; set; }
        public string Codes146 { get; set; }
        public string Codes147 { get; set; }
        public string Codes148 { get; set; }
        public string Codes149 { get; set; }
        public string Codes150 { get; set; }
        public string Codes151 { get; set; }
        public string Codes152 { get; set; }
        public string Codes153 { get; set; }
        public string Codes154 { get; set; }
        public string Codes155 { get; set; }
        public string Codes156 { get; set; }
        public string Codes157 { get; set; }
        public string Codes158 { get; set; }
        public string Codes159 { get; set; }
        public string Codes160 { get; set; }
        public string Codes161 { get; set; }
        public string Codes162 { get; set; }
        public string Codes163 { get; set; }
        public string Codes164 { get; set; }
        public string Codes165 { get; set; }
        public string Codes166 { get; set; }
        public string Codes167 { get; set; }
        public string Codes168 { get; set; }
        public string Codes169 { get; set; }
        public string Codes170 { get; set; }
        public string Codes171 { get; set; }
        public string Codes172 { get; set; }
        public string Codes173 { get; set; }
        public string Codes174 { get; set; }
        public string Codes175 { get; set; }
        public string Codes176 { get; set; }
        public string Codes177 { get; set; }
        public string Codes178 { get; set; }
        public string Codes179 { get; set; }
        public string Codes180 { get; set; }
        public string Codes181 { get; set; }
        public string Codes182 { get; set; }
        public string Codes183 { get; set; }
        public string Codes184 { get; set; }
        public string Codes185 { get; set; }
        public string Codes186 { get; set; }
        public string Codes187 { get; set; }
        public string Codes188 { get; set; }
        public string Codes190 { get; set; }
        public string Codes191 { get; set; }
        public string Codes192 { get; set; }
        public string Codes193 { get; set; }
        public string Codes194 { get; set; }
        public string Codes195 { get; set; }
        public string Codes196 { get; set; }
        public string Codes197 { get; set; }
        public string Codes198 { get; set; }
        public string Codes199 { get; set; }
        public string NumberOfFZEG { get; set; }
        public string Codes200 { get; set; }
        public virtual VehicleOrders VehicleOrders { get; set; }
    }
}
